#!/usr/bin/py


def raise_exception_msg(message=""):
    raise NameError(message)
